### ISSUE TITLE
Incompatible with Netmiko >=4.0.0

### ISSUE THREAD

**Issue by ohai89** [orange-cloudfoundry/napalm-cumulus#2]
As Netmiko 4.0.0 Release has the following:

- Relocate exceptions module to netmiko.exceptions (was ssh_exceptions)

cumulus.py will fail to load.

To enable compatibility, the reference needs to be changed in cumulus.py, line 38:

`from netmiko.ssh_exception import NetMikoTimeoutException`
to
`from netmiko.exceptions import NetMikoTimeoutException`

**Comment by justinbrink** [comment]
Here is a simple fix to support both.

```
--- a/napalm_cumulus/cumulus.py
+++ b/napalm_cumulus/cumulus.py
@@ -35,7 +35,10 @@ from napalm.base.exceptions import (
 )
 from napalm.base.utils import string_parsers
 from netmiko import ConnectHandler
-from netmiko.ssh_exception import NetMikoTimeoutException
+try:
+    from netmiko.ssh_exception import NetMikoTimeoutException
+except ModuleNotFoundError:
+    from netmiko.exceptions import NetMikoTimeoutException
 from pytz import timezone
 
```

**Comment by ohai89** [comment]
Hi, thank you for the tip @justinbrink .
Did not consider at all to use try-except clauses in the imports themselves.
